server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: http://localhost:8888
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/auth-service
            - JwtAuthFilter
        - id: account-service
          uri: http://localhost:8189
          predicates:
            - Path=/accounts/**
          filters:
            - StripPrefix=1
            - PrefixPath=/account-service
            - JwtAuthFilter
        - id: subscription-service
          uri: http://localhost:8193
          predicates:
            - Path=/subscriptions/**
          filters:
            - StripPrefix=1
            - PrefixPath=/auth-service
            - JwtAuthFilter
        - id: schedule-service
          uri: http://localhost:8191
          predicates:
            - Path=/schedule/**
          filters:
            - StripPrefix=1
            - PrefixPath=/auth-service
            - JwtAuthFilter

jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g

#logging:
#  level:
#    reactor:
#      netty: TRACE
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
